version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    volumes:
      - esdata_nf:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    ports:
      - 9200:9200
  filebeat:
    #user: root
    container_name: beat-container
    image: docker.elastic.co/beats/filebeat:8.0.0
    volumes: 
      - ./netflow.yml:/usr/share/filebeat/modules.d/netflow.yml
    networks:
      - "es-net"
    ports:
      - 2055:2055/udp
    depends_on:
      - "elasticsearch"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.0.0
    volumes:
      - kbdata_nf:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge
volumes:
  esdata_nf:
    driver: local
  kbdata_nf:
    driver: local